### Request 1
POST /api/auth/login/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "username": "user1",
    "password": "password1",
}
### Login Request
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "username": "admin",
    "password": "1234"
}