### Request 1
POST /api/auth/login/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "username": "user1",
    "password": "password1",
}
### Login Request
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "username": "admin",
    "password": "1234"
}

### request for /api/auth/user/ with access token
GET /api/auth/user/ HTTP/1.1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyNzAxNTgzLCJpYXQiOjE3MjI3MDEyODMsImp0aSI6Ijk3NzUyZTQ2NjhmMzQ4ZTRhZTBkODVjMzBlYmQ2M2M3IiwidXNlcl9pZCI6MX0.e7ZaiW-sCaDS5KnDkCpws5hUmehk89lDxUGi4a7OeeM


### request for /api/auth/logout/ with access token
POST /api/auth/logout/ HTTP/1.1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyNzAxNTgzLCJpYXQiOjE3MjI3MDEyODMsImp0aSI6Ijk3NzUyZTQ2NjhmMzQ4ZTRhZTBkODVjMzBlYmQ2M2M3IiwidXNlcl9pZCI6MX0.e7ZaiW-sCaDS5KnDkCpws5hUmehk89lDxUGi4a7OeeM