### Request 1
POST /api/auth/token/login/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "username": "user1",
    "password": "password1",
}
### Login Request
POST http://localhost:8000/api/auth/users/
Content-Type: application/json

{
    "username": "user1",
    "password": "1234",
    "re_password": "1234",
    "email": "user1@g.com"
}

### request for /api/auth/user/ with access token
GET /api/auth/user/ HTTP/1.1
Host: localhost:8000
Authorization: Token 84fc962144fc36b9448fc8e25537f67dec6db36d
### request for /api/auth/logout/ with access token


POST /api/auth/token/logout/ HTTP/1.1
Host: localhost:8000
Authorization: Token 84fc962144fc36b9448fc8e25537f67dec6db36d
